services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  proxy:
    image: secnex-reverse-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./proxy/certs:/app/certs

volumes:
  postgres_data:
